version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - .env
      - ./backend/.env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - ai
  frontend:
    build: ./frontend
    env_file:
      - .env
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  ai:
    build: ./python-ai
    env_file:
      - .env
      - ./python-ai/.env
    volumes:
      - ./python-ai:/app
    ports:
      - "5000:5000"
volumes:
  db-data:
