name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Verify Node and npm versions
        run: |
          node --version
          npm --version
          pwd
          ls -la

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --legacy-peer-deps
          echo "Dependencies installed successfully"

      - name: Create demo environment file
        run: |
          echo "REACT_APP_API_URL=/api" > .env
          echo "REACT_APP_DEMO_MODE=true" >> .env
          echo "REACT_APP_GITHUB_PAGES=true" >> .env
          echo "Environment file created:"
          cat .env


      - name: Build application
        run: |
          echo "Starting build process with GitHub Pages configuration..."
          npm run build:gh-pages
          echo "Build completed successfully"
          echo "Checking build directory contents..."
          ls -la build/
          echo "Checking index.html exists..."
          test -f build/index.html && echo "✅ index.html found" || echo "❌ index.html missing"
          echo "Content of index.html (first few lines):"
          head -5 build/index.html || echo "Could not read index.html"
          echo "Checking static assets..."
          ls -la build/static/ || echo "No static directory found"
        env:
          CI: false
          GENERATE_SOURCEMAP: false

      - name: Verify build success
        run: |
          echo "Verifying build artifacts..."
          if [ ! -f build/index.html ]; then
            echo "❌ ERROR: index.html not found in build directory"
            exit 1
          fi
          
          if [ ! -d build/static ]; then
            echo "❌ ERROR: static directory not found in build directory"
            exit 1
          fi
          
          echo "✅ Build verification successful"
          echo "📊 Build statistics:"
          find build -type f -name "*.js" | wc -l | xargs echo "JavaScript files:"
          find build -type f -name "*.css" | wc -l | xargs echo "CSS files:"
          du -sh build/ | xargs echo "Total build size:"

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4